Sets default theme to a Hacker Style theme
trypear/pearai-app pull request #294
Opened 2024-09-01 00:43 UTC by vedantgrover

Fixes #289 

This PR adds the palm-wave-ext package to the extensions folder and it adds palm-wave-ext as a built in extension. It also adds further configuration in the workbench to set the theme as the default value for the user. The user can still change the theme if needed.

2024-09-01 22:23 UTC, Fryingpannn commented
yoo, any screenshots? 👀

2024-09-02 03:53 UTC, vedantgrover commented
@Fryingpannn I gotchu bro

<img width="1022" alt="Screenshot 2024-09-01 at 23 48 48" src="https://github.com/user-attachments/assets/047aa6b0-e23a-4d71-a8ea-4b5aa9ecc89b">
<img width="1024" alt="Screenshot 2024-09-01 at 23 49 38" src="https://github.com/user-attachments/assets/c35c70e7-6483-4698-aca5-db9c7805a4e8">

2024-09-02 04:30 UTC, Himanshu-Singh-Chauhan requested changes

2024-09-02 04:30 UTC, Himanshu-Singh-Chauhan commented on src/vs/workbench/browser/workbench.ts
> +} from "vs/base/common/event";
don't change formatting, check your eslint or save without formatting from command pallete

2024-09-02 04:30 UTC, Himanshu-Singh-Chauhan commented on product.json
> +			"version": "0.0.3",
does this download it automatically from marketplace?

2024-09-02 04:30 UTC, Himanshu-Singh-Chauhan commented on src/vs/workbench/contrib/preferences/common/preferencesContribution.ts
> +	},
probably this can be removed

2024-09-02 04:30 UTC, Himanshu-Singh-Chauhan commented on product.json
> +			"repo": "https://github.com/RobertoGarc/palm-wave-ext/tree/main"
the repo is open source, but can we ship this theme in our app??
also we default theme might the pear theme that tanishq is working on.
gotta confirm with nang

2024-09-02 04:40 UTC, vedantgrover commented
Just FYI, I didn't have to configure anything. This is the default theme.

Not sure if the Issue wanted the **option** to switch to this theme or to use the theme as default. I think it's better to have it as default as it adds a bit of character and uniqueness to the app.

2024-09-02 04:41 UTC, vedantgrover commented on product.json
> +			"version": "0.0.3",
Yep

2024-09-04 21:31 UTC, nang-dev commented
this is good, but going to close this. I probably wasn't clear enough, but adding the extension is a bit too much. The color scheme is just a bunch of hex values, so we just want to hard code it in like:

https://github.com/trypear/pearai-submodule/pull/191

thanks sm though vedant, really appreciate this

2024-09-04 21:31 UTC, closed without merging