Rewrote the readme to be inline with issue: Fix readme #27
trypear/pearai-app pull request #30
Opened 2024-05-21 12:04 UTC by jwhitt3r

This PR addresses the issues outline in Fix readme #27 

I have reworked the page to link to the master document, included the contributing section to align with the contents of the document.

* Updated the features to be inline with the webpage
* Added a roadmap linking the master document
* Added a license section linking to your license model, I have removed the MIT license at the top as that is confusing with the actual document
* Added a contact section
* Added an acknowledgement section listing contributors
* Reworded the opening paragraph
* Reworked the page to include the Prerequisites of an OpenAI API key

2024-05-21 20:02 UTC, nang-dev commented
everything else looks good

2024-05-21 20:25 UTC, jwhitt3r commented
Glad everything looks good. Let me know if there are any issues ☺️

2024-05-21 21:18 UTC, jwhitt3r commented
Yea sure thing! Not a problem at all.

2024-05-21 21:22 UTC, jwhitt3r commented
All done.

2024-05-21 21:24 UTC, gedeondoescode approved these changes
Looks good! @nang-dev

2024-05-21 23:44 UTC, Fryingpannn requested changes
Nice work. Let's get these changes done then we can merge!

2024-05-21 23:44 UTC, Fryingpannn commented on README.md
> + 1. Remove the build and re-ran script `rm -rf out`
```suggestion
 1. Remove the build: `rm -rf out`
```

2024-05-21 23:44 UTC, Fryingpannn commented on README.md
> + 2. Re run `./scripts/code.sh` and retry
```suggestion
 2. Re-run the app: `./scripts/code.sh`
```

2024-05-21 23:44 UTC, Fryingpannn commented on README.md
> +Supercharge your development in an editor designed for less coding, with AI. Forked from VSCode, PearAI aims to deliver an enhanced development experience for all.
```suggestion
Speed up your development with an editor integrated with AI. PearAI is forked from VSCode, and aims to reduce the time from ideation to conception for your product development by achieving the most seamless integration with AI. By developers, for developers.
```

2024-05-21 23:44 UTC, Fryingpannn commented on README.md
> +This repository serves as the primary application for PearAI, with most functionalities housed within the extension/pearai submodule. We recommend focusing your work within this submodule by cloning
```suggestion
This repository serves as the primary application for PearAI, with most functionalities housed within the `extension/pearai` folder. We recommend focusing your work within this submodule by cloning it from https://github.com/trypear/pearai-app/.
```

2024-05-22 03:25 UTC, closed without merging

2024-05-22 03:42 UTC, nang-dev commented
Github force closed this upon refactor :(

2024-05-22 09:33 UTC, jwhitt3r commented
Can you reopen this?

2024-05-22 09:36 UTC, jwhitt3r commented on README.md
> + 1. Remove the build and re-ran script `rm -rf out`
I have resolved this.