Implement new shortcut `Shift+Cmd+L` for opening chat
trypear/pearai-app pull request #66
Opened 2024-05-24 03:52 UTC by happinyz

This PR implements https://github.com/trypear/pearai-app/issues/34.

The previous `Cmd+L` shortcut essentially did what @Fryingpannn wanted for the new `Shift+Cmd+L` command. The following changes are implemented in this PR:

- If the chat is closed, `Cmd+L` opens the previously selected chat. If there is no previously selected chat, opens a new chat.
- If the chat is open, `Cmd+L` does nothing.
- If the chat is closed, `Shift+Cmd+L` starts and opens a new chat.
- If the chat is open, `Shift+Cmd+L` starts a new chat.

https://github.com/trypear/pearai-app/assets/59787978/a5e51e9c-6d5b-4ddb-96df-eec99a83ba88

I have not implemented the code selection feature. Let's raise a new issue for that and I or someone else can make a new PR.

2024-05-24 05:06 UTC, cqdev-co requested changes
This looks pretty good, unfortunately your code didn't pass the checks: 
Checking formatting...
[warn] extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
[warn] extensions/pearai-extension/lib/extension/src/chat/ChatModel.ts
[warn] Code style issues found in 2 files. Run Prettier to fix.
error Command failed with exit code 1.

Other than that it looks ready to merge! Can you add shortcuts for Windows as well? I noticed you only did Mac.

2024-05-24 05:58 UTC, happinyz commented
Do we have a way to auto fix styling issues? `yarn nx lint` just warns me I have formatting issues but does nothing to fix them

2024-05-24 13:31 UTC, cwclancy reviewed
looks awesome, left some comments :)

2024-05-24 13:31 UTC, cwclancy commented on extensions/pearai-extension/package.json
> +        "key": "Shift+Cmd+l"
sorry don't know this file well, but do we need to add a "when": "isWindows" or something like that equivalent for it to work on windows? super concered we're going to end up making a shit windows app and most of our users will be there 😅

cc: @ItWasEnder Night

2024-05-24 13:31 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	 * @returns The last selected conversation.
imo you named the function so well that we don't need this comment.

2024-05-24 13:31 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +			await this.createConversation("chat-en");
we probably want to reflect that this function potentially creates a conversation in the function name. It might be more understandable if in open chat we have this logic, and it's like
1. if last chat exists, then open it
2. create new chat otherwise

2024-05-24 13:31 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +			await this.createConversation("chat-en");
just saw that this is nicely shared. yeah maybe just needs a different name. openMostRecentChatOrCreateNew or something like that haha

2024-05-24 14:54 UTC, happinyz commented on extensions/pearai-extension/package.json
> +        "key": "Shift+Cmd+l"
I saw that other implemented shortcuts use `!isMac` for linux/windows shortcuts: https://github.com/trypear/pearai-app/pull/66/files

2024-05-24 14:57 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	private async showConversation<T extends Conversation>(
let's also have this 
```
	private async addAndShowConversation(
		conversation: Conversation
	): Promise<Conversation> {
```

i'm not sure why they have the T here, but we don't need it and it makes the types more confusing. Also, this typing makes the input and return super clear so we can probably remove the comment as well

2024-05-24 15:00 UTC, cwclancy commented on extensions/pearai-extension/lib/common/src/webview-api/OutgoingMessage.ts
> +		type: zod.literal("openChat"),
can we pull this out into some like `ChatActions` file and same named enum? Then we can use it here, and in the `receivePanelMessage` switch so we don't accidently have a typo somewhere, we can start with this one and eventually migrate the rest of these there. Ideally we only write "startChat" once. I know that will be tough in the `.json` files, but we should be able to do it in the `.ts` files, especially the ones all under `pearai-extension`

2024-05-24 15:03 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/extension.ts
> +		vscode.commands.registerCommand("pearai.openChat", () => {
let's add a const here that's like `const PEAR_AI_COMMAND_PREFIX = 'pearai.` and then when we have the string enum for the command this line should look like `vscode.commands.registerCommand(PEAR_AI_COMMAND_PREFIX + CommandEnum.openChat)`

2024-05-24 20:39 UTC, cwclancy commented on extensions/pearai-extension/lib/common/src/webview-api/OutgoingMessage.ts
> +		type: zod.literal("openChat"),
IMO we can start doing the right thing in this change, no need fix anything other than new code you're introducing. The more we let this bad pattern go, the more people will continue to do the same thing, and we will have unmaintainable code.

2024-05-24 20:45 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	private async showConversation<T extends Conversation>(
I definitely won't block on "too many docs", but we should focus on making the code extremely readable, ideally so much so that docs aren't needed. 

In this case, param and return are self documenting. 

"Open and displays the specified conversation" feels pretty much the same as `openAndDisplayConversation(conversation)`, so I don't see tons of value in the comment.

2024-05-24 20:46 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	private async showConversation<T extends Conversation>(
we definitely need architecture documentation and people to have a better idea of how everything fits together. I thought @pan's was pretty useful for that!

2024-05-24 21:14 UTC, ItWasEnder commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	private async showConversation<T extends Conversation>(
yeah I probably should of added docu when going through that myself lol, but I'm not saying this current docu is good, it should really be changed to explain why it is an async function and what it is calling.

I also don't like verbose documentation, I just don't mind it lol. I'm the type of guy to say "this prints that" when the line below is "print(that)" 😂

2024-05-24 21:28 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/extension.ts
> +		vscode.commands.registerCommand("pearai.openChat", () => {
^^

2024-05-24 21:28 UTC, cwclancy commented on extensions/pearai-extension/lib/extension/src/extension.ts
> +		vscode.commands.registerCommand("pearai.openChat", () => {
^^

2024-05-26 20:11 UTC, happinyz commented on extensions/pearai-extension/lib/common/src/webview-api/OutgoingMessage.ts
> +		type: zod.literal("openChat"),
I'd like to keep this PR focused on just the shortcut change. I have a PR on my fork with the suggested qol changes: https://github.com/happinyz/pearai-app/pull/1. Once this PR is merged in, that PR can be targeted to this repo.

2024-05-26 20:13 UTC, happinyz commented on extensions/pearai-extension/lib/extension/src/chat/ChatController.ts
> +	private async showConversation<T extends Conversation>(
I agree with @cwclancy that things that are self documenting don't really need comments so I've removed what I think are repetitive comments.

2024-05-29 00:44 UTC, cqdev-co approved these changes

2024-05-29 06:05 UTC, Fryingpannn approved these changes
Thanks for this PR @happinyz 🫡

Great changes although unfortunately we will be replacing the `extensions/pearai-extension` folder by the new `extensions/pearai-submodule` folder which will allow us to speedrun to parity with Cursor. 

We will still need this feature in the new folder. Hopefully the knowledge acquired from this PR can transfer over!

Approving this and merging:)

2024-05-29 06:06 UTC, merged